### ISSUE TITLE
Parametros de Pesquisa com erro

### ISSUE THREAD

**Issue by kingabreel** [TCC-T-Academy-Grupo-5/car-price-compare-backend#21]
Algumas marcas retornam dois resultados, por serem usadas em dois tipos de veículos, nesse momento é retornado um erro no console e o filtro não é efetuado.

**Comment by paulohenrique-gh** [comment]
Não sei se ajuda, Gabriel, mas tem algumas marcas que tem o mesmo nome, mas o tipo de veículo é diferente. Por exemplo, Fiat tem carros e caminhões, então na tabela de brands tem Fiat duas vezes,  uma com tipo de veículo 0 (carro) e outra com tipo 2 (caminhão). Ficou assim devido à forma como está estruturado na tabela FIPE

**Comment by kingabreel** [comment]
Sim, vou colocar um deles como padrão quando a marca for null
